name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'  # Set the Go version you need

    - name: Build
      run: go build -o ./bin/dsync ./cmd/directory-sync

    - name: 'Upload Artifact'
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "./bin/**"
        release_id: ${{ github.event.release.id }}
        overwrite: true
        verbose: true
